"""Compatibility wrapper to the packaged MCP server implementation."""

from .service import (
    AttioClient,
    ConvexClient,
    OnceHubClient,
    append_person_note,
    book_oncehub_room,
    create_event,
    create_event_safe,
    ensure_speaker_for_person,
    find_oncehub_slots,
    flatten_record,
    flatten_speaker_entry,
    get_attendance_dashboard,
    get_contact,
    get_event,
    get_event_attendance,
    get_event_inbound_status,
    get_event_outreach,
    get_event_room_booking,
    get_person,
    get_speaker,
    list_events,
    mcp,
    search_contacts,
    search_people,
    search_speakers,
    update_event_safe,
    update_speaker_workflow,
    upsert_person,
)

__all__ = [
    "AttioClient",
    "ConvexClient",
    "OnceHubClient",
    "append_person_note",
    "book_oncehub_room",
    "create_event",
    "create_event_safe",
    "ensure_speaker_for_person",
    "find_oncehub_slots",
    "flatten_record",
    "flatten_speaker_entry",
    "get_attendance_dashboard",
    "get_contact",
    "get_event",
    "get_event_attendance",
    "get_event_inbound_status",
    "get_event_outreach",
    "get_event_room_booking",
    "get_person",
    "get_speaker",
    "list_events",
    "mcp",
    "search_contacts",
    "search_people",
    "search_speakers",
    "update_event_safe",
    "update_speaker_workflow",
    "upsert_person",
]


if __name__ == "__main__":
    mcp.run()
